log_level = "warn"
chef_client_ident = ""

[data_collector]
enable = "true"
server_url = ""
token = ""

[attributes]

  [attributes.camsa]
  firstname = ""
  lastname = ""
  emailaddress = ""
  username = ""
  password = ""
  license = ""
  managed_app = false
  gdpr = ""

    [attributes.camsa.cron]
    backup = ""
    certificate = ""

    [attributes.camsa.sa]
    name = ""
    container_name = ""
    access_key = ""

    [attributes.camsa.log_analytics]
    enabled = false

    [attributes.camsa.azure_functions.camsa]
    url = ""
    apikey = ""

    [attributes.camsa.azure_functions.central]
    url = ""
    apikey = ""

    [attributes.camsa.chefserver]
      [attributes.camsa.chefserver.org]
      name = ""
      description = ""

